//https://api.github.com/users/magentaspruce
export default {
  login: "MagentaSpruce",
  id: 81999424,
  node_id: "MDQ6VXNlcjgxOTk5NDI0",
  avatar_url: "https://avatars.githubusercontent.com/u/81999424?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/MagentaSpruce",
  html_url: "https://github.com/MagentaSpruce",
  followers_url: "https://api.github.com/users/MagentaSpruce/followers",
  following_url:
    "https://api.github.com/users/MagentaSpruce/following{/other_user}",
  gists_url: "https://api.github.com/users/MagentaSpruce/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/MagentaSpruce/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/MagentaSpruce/subscriptions",
  organizations_url: "https://api.github.com/users/MagentaSpruce/orgs",
  repos_url: "https://api.github.com/users/MagentaSpruce/repos",
  events_url: "https://api.github.com/users/MagentaSpruce/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/MagentaSpruce/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "www.sprucey.dev",
  location: null,
  email: null,
  hireable: null,
  bio: "Hi! I'm a full stack web developer. I enjoy doing work on both ends using React along with Node.JS.",
  twitter_username: "SpruceMagenta",
  public_repos: 73,
  public_gists: 0,
  followers: 2,
  following: 1,
  created_at: "2021-04-05T21:50:52Z",
  updated_at: "2021-07-28T20:57:11Z",
};
